### ISSUE TITLE
Not responsive 

### ISSUE THREAD

**Issue by E-fais** [ChristapherAntony/tinkerwatchesClone#1]
This website is not mobile responsive and hamburger menu is not working.

**Comment by ChristapherAntony** [comment]
Yaa its actually my first step to the world of HTML and CSS. Thanks for your Suggestion 👍

**Comment by E-fais** [comment]
Okay. If you are not working on responsiveness, You can assign me this issue.

**Comment by ChristapherAntony** [comment]
thanks bro

**Comment by ChristapherAntony** [comment]
Are you MERN Stack dev?

**Comment by E-fais** [comment]
I am react dev, currently learning node js  and mongo db.
